tap "b-ramsey/kali"
tap "browsh-org/browsh"
tap "coursier/formulas"
tap "felixkratz/formulae"
tap "gabe565/tap"
tap "homebrew/bundle"
tap "nikitabobko/tap"
tap "omnisharp/omnisharp-roslyn"
tap "sidaf/pentest"
tap "teamookla/speedtest"
tap "xwmx/taps"
brew "aha"
brew "air"
brew "aircrack-ng"
brew "amass"
brew "webp"
brew "apr"
brew "apr-util"
brew "arduino-cli"
brew "gcc"
brew "openblas"
brew "armadillo"
brew "as-tree"
brew "libxfixes"
brew "atuin"
brew "autoconf"
brew "automake"
brew "libgit2"
brew "bat"
brew "protobuf"
brew "bear"
brew "bettercap"
brew "icu4c@76"
brew "bfg"
brew "bison"
brew "blueutil"
brew "boost"
brew "bottom"
brew "btop"
brew "c"
brew "cabextract"
brew "certifi"
brew "chafa"
brew "clang-format"
brew "cmake"
brew "cmatrix"
brew "copilot"
brew "coreutils"
brew "cpanminus"
brew "ctags"
brew "libnghttp3"
brew "curl"
brew "direnv"
brew "docker", link: false
brew "dotnet"
brew "espeak-ng"
brew "ettercap"
brew "eza"
brew "fastfetch"
brew "fd"
brew "feh"
brew "unbound"
brew "sdl2"
brew "x264"
brew "x265"
brew "ffmpeg"
brew "ffuf"
brew "fish"
brew "flyctl"
brew "fontforge", link: false
brew "fzf"
brew "forgit"
brew "fswatch"
brew "gawk"
brew "gh"
brew "ghostscript"
brew "git"
brew "git-delta"
brew "git-filter-repo"
brew "git-lfs"
brew "git-secrets"
brew "glow"
brew "gnu-sed"
brew "lua"
brew "gnuplot"
brew "gsl"
brew "librtlsdr"
brew "portaudio"
brew "gnuradio"
brew "go"
brew "gobuster"
brew "graphviz"
brew "node"
brew "gtop"
brew "hashcat"
brew "htop"
brew "http-server"
brew "icu4c@75", link: true
brew "ifstat"
brew "libomp"
brew "libzip"
brew "imagemagick"
brew "john"
brew "jq"
brew "perl"
brew "latexml"
brew "lazydocker"
brew "lazygit"
brew "libffi"
brew "libimobiledevice"
brew "libpq", link: true
brew "libvterm"
brew "llama.cpp"
brew "llvm"
brew "lolcat"
brew "lsd"
brew "luajit"
brew "luarocks"
brew "mas"
brew "masscan"
brew "massdns"
brew "maven"
brew "mkcert"
brew "yt-dlp"
brew "mpv"
brew "mycli"
brew "mysql-client"
brew "ncdu"
brew "utf8proc"
brew "neovim"
brew "netcat"
brew "nginx"
brew "nikto"
brew "ninja"
brew "nmap"
brew "nowplaying-cli"
brew "nsnake"
brew "nyancat"
brew "oh-my-posh", link: false
brew "onefetch"
brew "openal-soft"
brew "openfst"
brew "p7zip"
brew "pandoc"
brew "petsc"
brew "picocom"
brew "pipes-sh"
brew "pipx"
brew "pnpm"
brew "poetry"
brew "procs"
brew "pv"
brew "pyenv"
brew "ripgrep"
brew "ruby"
brew "rustscan"
brew "scala"
brew "sentencepiece"
brew "sl"
brew "slides"
brew "sox"
brew "sqlmap"
brew "starship"
brew "subfinder"
brew "swig"
brew "switchaudio-osx"
brew "tcpdump"
brew "telnet"
brew "thefuck"
brew "theharvester"
brew "tmux"
brew "tokei"
brew "tree"
brew "tty-clock"
brew "typewritten"
brew "unzip"
brew "vim"
brew "watch"
brew "wget"
brew "winetricks"
brew "wireshark", link: false
brew "wxwidgets"
brew "xcodegen"
brew "yarn"
brew "yazi"
brew "zellij"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "coursier/formulas/coursier"
brew "felixkratz/formulae/sketchybar"
brew "teamookla/speedtest/speedtest"
brew "xwmx/taps/nb"
cask "aerospace"
cask "basictex"
cask "db-browser-for-sqlite"
cask "docker-desktop"
cask "firefox"
cask "font-fira-code"
cask "font-roboto"
cask "font-sf-mono"
cask "font-sf-pro"
cask "fontforge-app"
cask "hammerspoon"
cask "metasploit"
cask "mitmproxy"
cask "rnnoise"
cask "sf-symbols"
cask "wireshark-app"
mas "AdGuard for Safari", id: 1440147259
mas "CANAL+", id: 694580816
mas "Canva", id: 897446215
mas "Codye", id: 1516894961
mas "Color Widgets", id: 1531594277
mas "Coupert For Safari", id: 1531442936
mas "CSV Editor Pro X", id: 6477299212
mas "Cut the Rope 3", id: 997332884
mas "Developer", id: 640199958
mas "GeoGebra Graphing Calculator", id: 1294018688
mas "Git Streaks", id: 1525795950
mas "Grammarly for Safari", id: 1462114288
mas "GrandPerspective", id: 1111570163
mas "GRIS+", id: 1617349089
mas "Hand Mirror", id: 1502839586
mas "Icon Set Creator", id: 939343785
mas "Image2Icon", id: 992115977
mas "iMovie", id: 408981434
mas "InfinityGene", id: 6450520348
mas "keymapp", id: 6472865291
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "Live Wallpaper", id: 1456235760
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "MindNode", id: 1289197285
mas "MindNode Next", id: 6446116532
mas "Mini Motorways", id: 1456188526
mas "MyWallpaper", id: 1552826194
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Parcel", id: 639968404
mas "PiPifier", id: 1160374471
mas "Prime Video", id: 545519333
mas "RCT Classic+", id: 6702028686
mas "Skate City New York", id: 6448986810
mas "SPiNG", id: 1483542433
mas "The Last Campfire", id: 973039644
mas "The Unarchiver", id: 425424353
mas "WhatsApp", id: 310633997
go "github.com/air-verse/air"
go "github.com/bootdotdev/bootdev"
go "github.com/ajeetdsouza/clidle"
go "github.com/maaslalani/gambit"
go "github.com/maxpaulus43/go-sweep"
go "github.com/prime-run/go-typer"
go "github.com/szktkfm/mdtt/cmd/mdtt"
go "github.com/golang-migrate/migrate/v4/cmd/migrate"
go "github.com/saltfishpr/redis-viewer"
go "github.com/fedeztk/sku/cmd/sku"
go "github.com/brianstrauch/solitaire-tui"
go "github.com/mathaou/termdbms"
go "github.com/Broderick-Westrope/tetrigo/cmd/tetrigo"
